apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-manager
  namespace: server-manager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server-manager
  template:
    metadata:
      labels:
        app: server-manager
    spec:
      containers:
      - name: server-manager
        image: server-manager:latest
        ports:
        - containerPort: 8000
        env:
        - name: FLASK_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: url
        - name: REDIS_HOST
          value: "redis-service"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5 